kind: Service
apiVersion: v1
metadata:
  name: project-k-service
spec:
  selector:
    app: project-k-service
  ports:
    - protocol: TCP
      port: 8080
      nodePort: 30081
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-k-service
spec:
  selector:
    matchLabels:
      app: project-k-service
  replicas: 1
  template:
    metadata:
      labels:
        app: project-k-service
    spec:
      containers:
        - name: project-k-service
          image: naveenmanne/project-k
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: MONGO_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: username
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: password
            - name: MONGO_DB
              valueFrom:
                configMapKeyRef:
                  name: mongo-conf
                  key: database
            - name: MONGO_HOST
              valueFrom:
                configMapKeyRef:
                  name: mongo-conf
                  key: host
