swagger: "2.0"
info:
  version: "1.0.0"
  title: "Server API"
paths:
  /servers:
    get:
      summary: "Get all servers or get a single server by ID"
      parameters:
        - in: query
          name: id
          type: string
          description: "ID of the server to retrieve"
        - in: query
          name: name
          type: string
          description: "Name of the server to search for"
      responses:
        "200":
          description: "OK"
          schema:
            type: array
            items:
              $ref: "#/definitions/Server"
        "404":
          description: "Not Found"
    put:
      summary: "Create a server"
      parameters:
        - in: body
          name: body
          description: "Server object to create"
          schema:
            $ref: "#/definitions/Server"
      responses:
        "201":
          description: "Created"
          schema:
            $ref: "#/definitions/Server"
  /servers/{id}:
    delete:
      summary: "Delete a server by ID"
      parameters:
        - in: path
          name: id
          type: string
          required: true
          description: "ID of the server to delete"
      responses:
        "204":
          description: "No Content"
definitions:
  Server:
    type: object
    properties:
      id:
        type: string
        description: "ID of the server"
      name:
        type: string
        description: "Name of the server"
      language:
        type: string
        description: "Language of the server"
      framework:
        type: string
        description: "Framework of the server"
